### ISSUE TITLE
delete_after option

### ISSUE THREAD

**Issue by CodeNoobie17** [khk4912/EZPaginator#3]
A delete_after option would be a nice addition to this.

**Comment by khk4912** [comment]
You mean deleting the message?

**Comment by CodeNoobie17** [comment]
Yes, it would be nice to have an option to delete the contents after the reactions expire or after a set amount of time. This way the embed is not sitting in a channel with no options anymore.

**Comment by khk4912** [comment]
That would be great! Thanks for your suggestion.

**Comment by CodeNoobie17** [comment]
You're welcome, thanks for your quick reply and keep up the good work!

**Comment by CodeNoobie17** [comment]
Hey khk, do you have an eta on this feature? We have about 71 bots that could really use this.

**Comment by khk4912** [comment]
Sorry for the late update, Please check EZPaginator 1.3.4 which I've just uploaded. I added auto_delete option.
